### ISSUE TITLE
关于gpu内存管理

### ISSUE THREAD

**Issue by 18451627030** [Jihuai-wpy/SeqXGPT#10]
博主请问这个模型到底要多大显存才够跑，我租的24g的gpu只能同时挂gpt2、gptj、gptneo这三个模型，再调用llama的时候就会提示内存不够，当时当我用前面三个模型提取特征列表的时候发现根本提取不了一条特征，当我单用钢gpt2提取的时候发现大量的OOM，导致原来100条数据集只能提取出小几十条特征出来
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/115760396/93a8a5f3-b8d3-4de0-9a06-de6be659e387)

**Comment by 18451627030** [comment]
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/115760396/3dce8adc-9ef3-48cd-aa58-edba5b7d1afb)
还有在分好训练测试及后的训练和测试应该给哪些指令啊

**Comment by 18451627030** [comment]
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/115760396/d26376d5-6588-438f-94c9-55f8910d4f5d)
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/115760396/eb2238e7-cf75-4952-a40e-ee5544602aff)
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/115760396/ab75fd08-4600-4e3f-a017-33b999740edc)
就是目前我只能用gpt2和neo提取到的特征去复现一编 然后我修改了上面几处，有没有什么问题啊

**Comment by Jihuai-wpy** [comment]
请问你第一个问题中，是把几个模型同时部署在一个gpu上了吗？如果是一个的话理论上是不行的；但是如果是分别部署在4个gpu上那么是可行的。

**Comment by Jihuai-wpy** [comment]
整个的运行流程你可以看一下SeqXGPT/SeqXGPT/目录下的README.md

**Comment by 18451627030** [comment]
是的 我是同时部署在一个gpu上的，我是租的autodl，可以同时租几个？

**Comment by Jihuai-wpy** [comment]
感觉修改成两个之后的代码应该是对的。

**Comment by Jihuai-wpy** [comment]
这个我也没用过，但其实你也可以一个模型一个模型的提取特征，之后合并一下文件就行。这样一个gpu也能跑

**Comment by 18451627030** [comment]
谢谢
在训练测试的时候给哪些指令啊
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/115760396/a0584687-cc20-45f5-ae09-dba8a21057a8)
这样好像不行

**Comment by Jihuai-wpy** [comment]
训练你就直接跑
\# train
这行注释下面的这个命令就行。

**Comment by 18451627030** [comment]
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/115760396/8347c707-d676-48e6-8251-68c6cb854e07)
他会包这样的错误

**Comment by Jihuai-wpy** [comment]
时间太久了有点忘了，刚刚看了下，应该是你没有传路径进去，你可以在命令行中--train_path设置一下，或者你在train.py文件夹下，有个parse_args()函数，原本一些固定的参数我就默认在里面设置了，你也可以在这里设置默认值。

**Comment by 18451627030** [comment]
十分感谢！

**Comment by Jihuai-wpy** [comment]
不客气啦~~
