### ISSUE TITLE
http连接超时

### ISSUE THREAD

**Issue by Ehrgeiz-H** [Jihuai-wpy/SeqXGPT#11]
inference服务器成功启动之后运行特征提取连接超时

![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/110002941/d855bed7-abdd-486b-94e0-8bacedf85bb2)
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/110002941/11c10786-9ad7-4e78-bbff-910663e279ab)
![image](https://github.com/Jihuai-wpy/SeqXGPT/assets/110002941/21289897-9d07-44ba-bbf9-4c4c955954bf)

**Comment by Jihuai-wpy** [comment]
Hello，这应该是你提供的inference model的地址不正确。之前有位同学问过相关的问题了，在 https://github.com/Jihuai-wpy/SeqXGPT/issues/5 有非常详细的QA，请你先参考一下，如果还有问题请再次提问。

**Comment by Jihuai-wpy** [comment]
感觉就几方面需要注意，一个是你需要把默认代码中的inference model的地址换成你自己的；另外一个可能复杂一些，涉及到网络穿透（如果你是多个服务器上）；还有一个关于windows的问题，也在issue 5中，里面有我尝试的解决方案~~你可以先试一下~
