### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by peterwan1** [Jihuai-wpy/SeqXGPT#14]
①如果想用中文数据集测试的话，代码中的damo模型具体指的是哪一个模型呢
②文章中的OOD，document实验是在使用bench做训练集的基础上吗
③Particular-Model Binary AIGT Detection的实验结果是使用特定model+human的训练集训练的呢，还是正常multi方法的训练，拿出来测试集中的特定model/human测试的呢
感谢！

**Comment by Jihuai-wpy** [comment]
问题1：这个模型来自于modelscope，https://modelscope.cn/models/iic/nlp_gpt3_text-generation_2.7B/quickstart
问题2：OOD的意思就是构造数据时使用的人类数据跟训练集使用的人类数据不是同一批。document构造数据时使用的人类数据跟训练集使用的人类数据则是同一批。
问题3：你理解的是对的，是particular model的数据和human的数据。

**Comment by peterwan1** [comment]
①我在使用damo还有wenzhong时一直报错，damo的报错忘记记录了，应该是一些编译c语言的包的安装报错；wenzhong的报错是：RuntimeError: where expected condition to be a boolean tensor, but got a tensor with dtype Half，我搞不清是什么原因
②我的意思是在做文章中的测试的时候，OOD，document部分的实验，是在用bench做训练集，OOD/document做测试集进行的吗，因为我看后二者数据量比较小，按我的理解应该不是再把OOD/document分为训练集和测试集
③也就是说按照多分类进行训练，测试的时候只拿测试集的particular model的数据和human的数据对吗。（如果是这样，测试的时候使用的是particular model的数据，还是human数据也使用，因为particular model的数据中后半段也是human，如果再加入human数据集会不会造成数据不均衡）
抱歉打扰，再次感谢！

**Comment by Jihuai-wpy** [comment]
问题1：这两个模型就是使用起来很麻烦，可能涉及到一些环境的问题。对了，你可以在sniffer的官方仓库中找下requirement试试。因为seqxgpt并没有在中文上跑，但是我们在做sniffer实验的时候是都跑了的。这个是sniffer github仓库的链接：https://github.com/OpenLMLab/Sniffer 。其实你也可以用当下别的一些模型，比如在中文数据上训练过的llama系列。
问题2：用之前训好的模型直接测，OOD和document是测试集。
问题3：不是，比如我们测particular model binary的时候，只用GPT2和human训，然后在对应的测试集上测就行。

**Comment by peterwan1** [comment]
这三个问题都明白了，谢谢！
