### ISSUE TITLE
关于对齐的问题

### ISSUE THREAD

**Issue by peterwan1** [Jihuai-wpy/SeqXGPT#15]
我看了代码中align的部分，不知道我的理解是不是正确，想请教一下😀：
①以BBPE为例，我的理解是：核心思想是token和word的最小单元都是byte，logp是以token为单位的，token是好多个byte，每个byte的logp都相等，而word是好多byte组成的，word的logp可以是这些byte各种logp的平均值。因为无论什么tokenizer，token不同，但句子分词都到的词是一样的，利用这一点统一各种tokenizer。不知道我的理解正确吗
②我看到skywork模型用的是是CharLevelTokenizerPPLCalc，但是skywork论文中说的是和llama一样使用sentencepiece的BPE，不知道这里的CharLevelTokenizer是怎么知道的呀
③代码中的TikTokenizerPPLCalc是什么意思，我没有看到有使用这个类

**Comment by Jihuai-wpy** [comment]
问题一：完全正确！就是先化整为零，然后重新组合。
问题二：有的其实是我试出来的。paper我没有具体看，但我通过观察词表以及tokenizer的行为做出的判断。
问题三：这个是当时放出的chatGPT的tokenizer，他们tokenizer的库就是这个名字，hhhh。
