### ISSUE TITLE
Prompt_len

### ISSUE THREAD

**Issue by caseware66** [Jihuai-wpy/SeqXGPT#19]
您好，在测试的数据里我看human是没有这个值的，但是代码里是用到了，这个应该怎么处理？

**Comment by Jihuai-wpy** [comment]
因为human数据中整段文本的来源都是human-created，那直接将其prompt_len设置为len(text)即可。
PS：实际上在sentence-level detection任务中，因为gpt2, llama等每个数据中，一部分是human生成的，一部分是AI生成的；且其中human生成部分正好是human数据集中的句子，因此测试的时候可以不用测试human数据集。当然也可以测试~

**Comment by caseware66** [comment]
> 因为human数据中整段文本的来源都是human-created，那直接将其prompt_len设置为len(text)即可。 PS：实际上在sentence-level detection任务中，因为gpt2, llama等每个数据中，一部分是human生成的，一部分是AI生成的；且其中human生成部分正好是human数据集中的句子，因此测试的时候可以不用测试human数据集。当然也可以测试~

谢谢！

**Comment by caseware66** [comment]
您好，在运行中有遇到这个错误吗？RuntimeError: Given groups=1, weight of size [64, 1, 5], expected input[2, 0, 512] to have 1 channels, but got 0 channels instead

**Comment by Jihuai-wpy** [comment]
感觉好像是CNN+Transformer那一步报错了，如果你能给我更详细的报错内容，我会很高兴帮助您

**Comment by caseware66** [comment]
我大概知道了，是因为我只使用了两个接口服务，因此我需要修改model里的卷积

**Comment by Jihuai-wpy** [comment]
好的
