### ISSUE TITLE
特征提取得到的output.jsonl为空

### ISSUE THREAD

**Issue by zzyzeyuan** [Jihuai-wpy/SeqXGPT#2]
您好，我在执行这一步时，得到了空的output.jsonl文件：
```
python gen_features.py --get_en_features --input_file ./SeqXGPT-Bench/en_gpt2_lines.jsonl  --output_file output.jsonl
```
另外，我使用的是gpt2-xl，由于我是offline模式，所以我在`gen_features.py`中将`gpt_2_api`修改成了`http://0.0.0.0:6006/inference`, 其中`0.0.0.0:6006`是启动server时得到的信息。

在运行`gen_features.py`时，命令行中会显示`return NoneType, probably gpu OOM, discard this sample`，应该是出现TypeError了，但是具体原因还望能请教一下，希望能得到您的帮助！

**Comment by Jihuai-wpy** [comment]
gen_features.py这个文件中，一次性要提取4个inference模型的特征，并且如果任何一个inference模型的api访问失败都会出现上面的错误信息。
看你的提问，应该是gpt2的api传好了，那你其他几个模型的api是否也传好了？或者是否注释掉了。

**Comment by Jihuai-wpy** [comment]
你可以看看启动gpt2后的后台打印信息，如果那边显示的信息看起来调用正常，说明可能是我上面所说的问题，如果不是，希望你告知更详细的问题信息，我会尽全力帮你解决~

**Comment by zzyzeyuan** [comment]
> 你可以看看启动gpt2后的后台打印信息，如果那边显示的信息看起来调用正常，说明可能是我上面所说的问题，如果不是，希望你告知更详细的问题信息，我会尽全力帮你解决~

我检查了一下gpt2后台信息，没有出现ERROR，都是DEBUG。 我现在把`en_model_apis`中除了`gpt_2_api`以外的api都注释掉了，目前看来一切ok，大概需要20min才能提取完所有特征。

非常感谢你及时的回复和帮助, 
nice job.

**Comment by Jihuai-wpy** [comment]
好的好的，这样一来，你可以分四次提取各个模型的特征，最后写个简单的代码合并四组特征，之后应该就可以原原本本地使用其他代码啦~
嘿嘿，很高兴帮到你，后续如有问题随时找我~

**Comment by zzyzeyuan** [comment]
> 好的好的，这样一来，你可以分四次提取各个模型的特征，最后写个简单的代码合并四组特征，之后应该就可以原原本本地使用其他代码啦~ 嘿嘿，很高兴帮到你，后续如有问题随时找我~

hi, 从昨天到现在我都在尽力克服网络原因(不能直接从huggingface上调取model)。不过现在gpt-J和llama2似乎难以解决。

所以我想请问一下，能否只用gpt-2和gpt-neo两个模型来提取paper里的foundational features? 

非常感谢！

**Comment by Jihuai-wpy** [comment]
肯定是可以的，我们这里提取foundation features时可以用任意多的模型。但是如果只用两个的话，可能会造成模型性能大幅度下降。
