### ISSUE TITLE
用gpt3生成训练数据

### ISSUE THREAD

**Issue by caseware66** [Jihuai-wpy/SeqXGPT#20]
您好，我想要gpt去生成一些训练数据，是在human的截取前几句的基础上生成吗？生成的时候提示应该怎么写最好

**Comment by Jihuai-wpy** [comment]
是的，是在给定前几句的基础上生成即可。如果是预训练模型，直接给前几个句子即可，如果是chat model，那么需要通过指令让其理解你的需求，这里可以给你一个例子供你参考下：
Given the provided input text, continue writing a text passage that logically and coherently extends the initial content.
Input text: {text}
实际上你也可以prompt ChatGPT让它帮忙生成提示，比如你告诉它你的需求，让它帮你写一个指令。
希望上面的回复能帮助到你~
