### ISSUE TITLE
按照gen_features.py得到的jsonl文件中有键值缺失

### ISSUE THREAD

**Issue by zzyzeyuan** [Jihuai-wpy/SeqXGPT#3]
你好，使用`python ./dataset/gen_features.py --process_features`得到的jsonl文件中，缺少了dataloader.py文件中所需要的键值：`prompt_len`, `begin_idx_list`, `ll_tokens_list` (分别对应第77,88,89行)，请问要怎么处理呢？

目前通过`python ./dataset/gen_features.py --process_features`得到的jsonl文件的格式如下：
```
{"values": {"losses": , 
             "lt_zero_percents": , 
             "std_deviations": , 
             "pearson_list": , 
             "spearmann_list": }, 
  "label_int": 0, 
  "label": "gpt2", 
  "text": "}
```

**Comment by zzyzeyuan** [comment]
我发现使用`python ./dataset/gen_features.py --get_en_features`得到的jsonl不缺少`begin_idx_list`和`ll_tokens_list`， 但是仍然缺少`prompt_len`。 只有原始的`./SeqXGPT-Bench/`目录下的数据是包括了`prompt_len`的，但是又并不包含`begin_idx_list`和`ll_tokens_list`。

所以我对使用的数据很困惑，希望能得到你的帮助！

**Comment by Jihuai-wpy** [comment]
好的，下面我先回答一下关于数据相关的问题：

我们主实验如论文所说，可以做句子级别的检测。因此，我们的每一条样本（也就是数据集的一个line['text']）中，前面1-3条句子是human生成的，而后面的句子是模型生成的。正常情况下，肯定是标记一下，前面多少条句子是human生成的，来确定这个边界，但是为了方便在python中处理，我们引入了prompt_len。因为我们的line['text']都是str，即字符串，line['text'][:prompt_len]刚好代表了human生成部分，line['text'][prompt_len:]则表示模型生成的部分。

SeqXGPT-bench和OOD sentence-level detection dataset这两个数据集，我们是做sentence-level detection，因此，除了human的数据集，其他所有的数据集都会有prompt_len，来确定一个'text'中哪部分是human生成的，剩下的是模型生成的。

另外一个数据集document-level detection dataset，则是整段都是由模型生成的，因此相当于prompt_len是0；该数据集下的human_lines.jsonl中，所有的line['text']都是由human生成的，相当于prompt_len=len(text)。

希望这个问题我在这里回答清楚了，如果有问题，还请随时提问~

**Comment by Jihuai-wpy** [comment]
然后是关于gen_features.py这个文件。这个文件中有两个函数：

get_features(): 输入是原始的lines.jsonl文件，输出的是从我们每个inference model中提取到的初始特征，result = {'losses': losses, 'begin_idx_list': begin_idx_list,  'll_tokens_list': ll_tokens_list, 'label_int': label_int, 'label': label, 'text': line }。如果因为显存、机器等问题，可能inference model一次只能部署一个，那可以分别提取，最后注意，'losses', 'begin_idx_list',  'll_tokens_list'这几个需要合并起来。您可以看一下这里的代码：
```
for api in model_apis:
                try:
                    loss, begin_word_idx, ll_tokens = access_api(line, api)
                except TypeError:
                    print("return NoneType, probably gpu OOM, discard this sample")
                    error_flag = True
                    break
                losses.append(loss)
                begin_idx_list.append(begin_word_idx)
                ll_tokens_list.append(ll_tokens)
```
可以看到，实际上就是把每次提取到的loss, begin_word_idx, ll_tokens，合并到losses，begin_idx_list，ll_tokens_list中。这里我们默认可以有四个inference model，当然**您也可以只有三个inference model，甚至可以有五个六个，更多个，这里都是可以的**。（这里着重回答一下，是因为我看到您邮件提到了这个问题，特别回答一下~）


process_features(): 这个函数的输入文件，则是经过上一轮get_features()处理之后的文件，特别地，已经有了losses，begin_idx_list，ll_tokens_list我们提取到的初始特征。因此这里，我们确实要process features，就是将提取到的初始特征进一步处理，来完成sniffer相关的baseline实验。因此，这个函数实际上是SeqXGPT不需要用到的。


希望我的回答能解决您目前遇到的困惑，如您还有问题，欢迎随时提问~

**Comment by Jihuai-wpy** [comment]
综上，您可以在gen_features.py中的gen_feautres()中增加一行，就是判断一下如果line有键值为prompt_len，那么在results中也保留它。应该就可以解决问题了~

**Comment by zzyzeyuan** [comment]
非常非常感谢您的帮助。按照您的提示，我修改了gen_features()中的代码，缺失键值的问题已经解决了。

非常感谢！

**Comment by zzyzeyuan** [comment]
您好，还有另外一个问题。由于资源有限，我现在只取目录`./SeqXGPT-Bench/`下的`gpt2`,`gptneo`,`gptj`, `human`四个文件的前200行来跑通代码，所以一共是800条数据。按照默认的训练集90%、测试集10%的设定，在`train.py`中`seq_len`参数（默认是1024）应该设定为多少比较合适呢？

现在我直接运行 `python ./SeqXGPT/train.py --gpu=4 --split_dataset --model Transformer`会得到以下报错：
```
RuntimeError: Given groups=1, weight of size [64, 1, 5], expected input[32, 0, 1024] to have 1 channels, 
but got 0 channels instead```

**Comment by Jihuai-wpy** [comment]
OKOK，下面我详细为您解答一下您的两个问题：

问题一：关于Seq_len的大小问题。这个建议还是至少保持默认的1024，有以下几个原因：一，我们进行的是细粒度的AIGT检测，如果Seq_len太短，可能导致没有办法分隔开哪部分是human生成的，哪部分是AI生成的。二，我们的SeqXGPT模型本身很小，需要的资源也非常少。因此您完全可以调小batch size，来保持seq_len不变。

问题二：我去看了一下，这里的错误是因为CNN处理的问题。请您看一下model.py 148-153行的代码，原本因为我们用了四个特征list，所以我拆出了out1, out2, out3, out4，但我记得您似乎只用了两个。您可以修改下这里就行。这里也是我代码不优美的地方，这里理应使用循环代码处理，而不是手动遍历。还请您先自行修改一下。之后我们会统一重新修改一版代码。
具体修改，您用了几个特征list，就拆几个出来，对应的153行就传进去几个。但此时，112行原本是4*64，代表有来自4个不同特征list转变而来的64维特征，现在你需要修改成你用的特征list的数量。


希望我的回复对您有帮助。

**Comment by Jihuai-wpy** [comment]
您可以比如给这个类加一个参数进去，这个参数控制您使用的特征list的数量（inference model的数量），这样，比如您增加了新的特征list的数量之后，直接改一下传入的这个参数的值即可。

**Comment by zzyzeyuan** [comment]
> 您可以比如给这个类加一个参数进去，这个参数控制您使用的特征list的数量（inference model的数量），这样，比如您增加了新的特征list的数量之后，直接改一下传入的这个参数的值即可。

您的帮助太详细啦！ 非常感谢，您解答了我这么多的问题~
