### ISSUE TITLE
关于生成foundation features时GPU内存管理

### ISSUE THREAD

**Issue by zzyzeyuan** [Jihuai-wpy/SeqXGPT#4]
你好，
在计算资源有限的情况下，我每一次只部署一个模型来生成foundation features。但是由于我的GPU显存只有16G，所以在只部署一个模型的情况下，GPU内存也会吃不消。

我看了一下gpt2的代码，只是通过`self.model.to(device)`把模型放到GPU内存中了。我尝试了torch.cuda.empty_cache()，但并没有作用。另外，生成feature和batch_size也无关，看起来只是因为我的GPU内存放不下gpt2这个模型（更别说其他更大的模型了）。

在这种情况下，有什么办法可以节省GPU内存吗？

**Comment by zzyzeyuan** [comment]
我记得您之前提到说尽量保持seq_len =1024，那是否可以稍微减小一点seq_len？或者做模型量化，让模型本身小一点

**Comment by Jihuai-wpy** [comment]
seq_len可以小一点。但我记得您说过您的需求文本长度一般都比较长，所以可能尽量seq_len不要减少。您可以load tokenizer，tokenize你的document试试看，平均tokenize时候的长度大概有多长。
可以让模型量化，比如可以load_in_8bit。这个我们试过对性能的影响可能不大。

**Comment by Jihuai-wpy** [comment]
我刚刚重新check了一下代码，暂时没想到更多的办法，想请问一下，你是一次inference都不行，还是跑了几次之后才报了OOM呀。

**Comment by zzyzeyuan** [comment]
模型准确度下降我目前可以接受，现在的目标是尽可能减小GPU显存占用。

我刚刚尝试了一下给gpt2模型也`load_in_8bit=True`，不过得到了这个错误：
```
ValueError: `.to` is not supported for `8-bit` models. 
Please use the model as it is, since the model has already been 
set to the correct devices and casted to the correct `dtype`.
```

**Comment by zzyzeyuan** [comment]
> 我刚刚重新check了一下代码，暂时没想到更多的办法，想请问一下，你是一次inference都不行，还是跑了几次之后才报了OOM呀。

我目前取了200个来做inference，大概会有20个左右OOM

**Comment by zzyzeyuan** [comment]
没关系，谢谢你及时的回复。受限于计算资源，可能最好的办法就是买机器hhhhhhh。

**Comment by zzyzeyuan** [comment]
我猜测200个中OOM掉的这个20个，应该就是比平均token长度更长一点的文本，刚刚好超出了16G的限制

**Comment by zzyzeyuan** [comment]
如果我把[gpt2-xl, gptneo, gptj, llama]中的gpt2-xl替换成gpt2-large，精度会损失很多吗？我想这也许是一个解决办法

**Comment by Jihuai-wpy** [comment]
我记得部署模型之后，如果OOM了可能并不影响后面的inference。就如果训练数据损失一部分应该也影响不大，你也可以事先处理一下，不要让数据太长。

**Comment by Jihuai-wpy** [comment]
> 模型准确度下降我目前可以接受，现在的目标是尽可能减小GPU显存占用。
> 
> 我刚刚尝试了一下给gpt2模型也`load_in_8bit=True`，不过得到了这个错误：
> 
> ```
> ValueError: `.to` is not supported for `8-bit` models. 
> Please use the model as it is, since the model has already been 
> set to the correct devices and casted to the correct `dtype`.
> ```

这个我想起来了，好像gpt2这么做是会报错的。

**Comment by Jihuai-wpy** [comment]
> 如果我把[gpt2-xl, gptneo, gptj, llama]中的gpt2-xl替换成gpt2-large，精度会损失很多吗？我想这也许是一个解决办法

这个应该也是可以的，就你维护的inference model，本质上是不受限制的。你甚至可以维护更多的模型。

**Comment by zzyzeyuan** [comment]
> > 模型准确度下降我目前可以接受，现在的目标是尽可能减小GPU显存占用。
> > 我刚刚尝试了一下给gpt2模型也`load_in_8bit=True`，不过得到了这个错误：
> > ```
> > ValueError: `.to` is not supported for `8-bit` models. 
> > Please use the model as it is, since the model has already been 
> > set to the correct devices and casted to the correct `dtype`.
> > ```
> 
> 这个我想起来了，好像gpt2这么做是会报错的。

另外，我印象中模型的量化是可以选择8bit或者4bit, 我尝试了gptneo和gptj的4bit量化`load_in_4bit`，发现都会报错：
```
TypeError: __init__() got an unexpected keyword argument 'load_in_4bit'
```
这是模型默认只能8bit量化吗？

**Comment by Jihuai-wpy** [comment]
就是有这种工作指的是有人做了相关的工作。但如果我们仅仅通过一个参数就进行修改，那可能需要的是huggingface去帮我们实现。如果没有实现，就不能直接这么用。所以现在的情况可能是huggingface并没有实现这个。

**Comment by zzyzeyuan** [comment]
> 就是有这种工作指的是有人做了相关的工作。但如果我们仅仅通过一个参数就进行修改，那可能需要的是huggingface去帮我们实现。如果没有实现，就不能直接这么用。所以现在的情况可能是huggingface并没有实现这个。

OK, 我先尝试用小一点的模型跑起来！ 感谢解答了我提的3个issue。

**Comment by Jihuai-wpy** [comment]
好的好的，加油！
