### ISSUE TITLE
在缺失label字段的情况下，viterbi_decode里的mask如何处理

### ISSUE THREAD

**Issue by gqq1210** [Jihuai-wpy/SeqXGPT#7]
Hi, 我目前正在尝试直接用SeqXGPT在测试集上做推理。假设测试集一共10000条数据，我不需要划分数据，直接将这1万条数据作为测试集进行推理，但是测试集上没有`label`字段。因此，在`model.py`文件的`class ModelWiseTransformerClassifier`的forward函数中，无法传入labels参数，从而不能得到mask，使得self.crf.viterbi_decode也缺失了mask参数的值，导致推理无法进行。(另外，我也试过了将viterbi_decoder的mask设置为None，但似乎这个参数是必须的)

请问在缺失label字段的情况下，viterbi_decode这里的mask要怎么处理呢？

**Comment by Jihuai-wpy** [comment]
不好意思没能非常及时的回复您。请问您现在解决问题了吗？

这个问题可以尝试这样解决：这里的labels实际上有两个作用，一个是给出真实的标签，一个是表示哪些地方是实际的word，哪些地方是padding的。只有训练时，我们才需要用到真实的标签；测试时，我们实际上只需要利用labels指出哪些是真是需要预测的位置，哪些是被padding的位置。因此，我们可以继续沿用dataloader，但是给一个“伪标签”。最后我们根据output来确定我们最终的预测就可以了。我们仅仅利用伪标签来帮助我们确定padding位置即可。

或者您也可以在现有代码的基础上，一边传入真实的标签labels，也传入masks。这样，测试时我们只传入masks即可，不需要传入labels。

希望我的回复对您有帮助~
