### ISSUE TITLE
About begin_idx_list

### ISSUE THREAD

**Issue by zzyzeyuan** [Jihuai-wpy/SeqXGPT#8]
Hi, 我使用gen_featuer.py生成的文本embeddings(也就是ll_tokens_list)每一项的第一个数值都不是0.0，那么是不是对应的begin_idx_list应该改为[0,0,0,0]？

**Comment by Jihuai-wpy** [comment]
一般情况是应该不是0。因为我们是计算每个token预测的logP，但是对于GPT2这种模型，我们是直接将句子送进去，我记得默认是没有BOS，所以第一个token是无法计算logP的，因此一般情况下，跟第一个token相关的word，其logP也是无法计算的。
所以，请您放心用，这里是没有问题的。
