### ISSUE TITLE
请问有没有已经训练好的模型可以直接拿来推理？

### ISSUE THREAD

**Issue by Kamichanw** [Jihuai-wpy/SeqXGPT#9]
另外如果把transformer换成deberta会不会带来进一步的提升？

**Comment by Jihuai-wpy** [comment]
这个我没有具体尝试过。但我觉得可以一试~

**Comment by Kamichanw** [comment]
看了readme之后，我想问一下总结一下在自己的数据集上训练document level classification的流程，如有疏漏烦请您指正。
- 把自己的训练集改成符合以下格式的文件：
```json
{
    "text": "...",
    "label": "human" 
}
```
由于我只分类为human和AI，所以label取human或AI。
相似地，测试集改成
```json
{
    "text": "..."
}
```
- 将此处的代码取消注释：https://github.com/Jihuai-wpy/SeqXGPT/blob/da2f264160c12a95c9573c4820fefaa75a68a0f9/SeqXGPT/SeqXGPT/train.py#L349
- 使用如下代码提取features
```bash
python ./dataset/gen_features.py --get_en_features --input_file input.jsonl --output_file output.jsonl
```
- 使用如下代码进行训练和测试：
```
# train
python ./Seq_train/train.py --gpu=0 --train --data_path path/to/output.jsonl

# test document-level AIGT detection
python ./Seq_train/train.py --gpu=0 --do_test --test_content --test_path path/to/testset.json
```

我觉得我训练和测试的理解可能不太正确，但是受限于我匮乏的知识，我无法从您的代码了解到更多了:(

**Comment by Jihuai-wpy** [comment]
是的是的，您的整体思路完全没有问题！我觉得完全正确！如果您在复现的过程中遇到任何问题，欢迎您随时提问，我会尽量及时给您回复~~~

**Comment by Kamichanw** [comment]
我想知道我应该如何使用`gen_feature.py`来为我的数据集提取特征？因为我的数据集只包含AI和human，不区分LLMs。然而据我观察代码，`gen_feature.py`似乎和特定的模型息息相关。

**Comment by Jihuai-wpy** [comment]
是这样子的，用于提取特征的inference model，也就是gen_features.py中使用的model，跟我们的具体的label是没有关系的。我们是将inference model中得到的logP list作为特征，我们的inference model可以是gpt2, gptneo, gptj, llama，当然我们可以用更多的模型或者别的模型。
而标签是我们需要预测的类别。我们根据前面提取到的特征，来训练一个分类器模型，用于预测一句话的类别。我们的类别可以是二元的AI/human，也可以是更细粒度的标签。

也就是说，inference model确实和特定的模型息息相关，但inference model决定的是我们提取的特征的来源；
而数据集的标签决定的是我们最终要预测的类别。

故此，标签和inference model没有必然的联系。

希望我的回复能够解答您的疑问。如果您还有问题或者我没有解释清楚，请随时提问~~~

**Comment by peterwan1** [comment]
> 另外如果把transformer换成deberta会不会带来进一步的提升？

这里可以用deberta吗，我试了之后一直报错，因为huggingface的deberta的输入和这里cnn处理之后的logp特征好像不太一样，deberta的输入要求是input_ids，都是整数
还是说我哪里理解的有问题呢
